#!/usr/bin/env python3
"""Extract text and equation-like labels from Ribarik-PhD-Thesis.pdf.

Outputs:
  - data/thesis_text/full_text.txt
  - data/thesis_text/equation_index.md
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


EQUATION_LABEL_PATTERNS = [
    # Common numbered-equation forms: (2.3), (10.14a), (A.1)
    re.compile(r"\(([A-Z]?\d+(?:\.\d+)+(?:[a-z])?)\)"),
    # Sometimes equation markers are chapter-prefixed with dash: 2-14
    re.compile(r"\b([A-Z]?\d+-\d+(?:[a-z])?)\b"),
]


def _load_pdf_reader(pdf_path: Path):
    try:
        from pypdf import PdfReader
    except Exception as exc:  # pragma: no cover - import error path
        raise RuntimeError(
            "Missing dependency 'pypdf'. Install with: python -m pip install pypdf"
        ) from exc

    return PdfReader(str(pdf_path))


def _extract_equation_records(page_text: str, page_number: int) -> list[tuple[str, int, str]]:
    records: list[tuple[str, int, str]] = []
    for raw_line in page_text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        labels: set[str] = set()
        for pattern in EQUATION_LABEL_PATTERNS:
            labels.update(match.group(1) for match in pattern.finditer(line))

        if not labels:
            continue

        # Heuristic: only keep lines likely to describe/display equations.
        if not any(token in line for token in ["=", "β", "α", "γ", "Δ", "sin", "cos", "ln", "exp", "MWP", "CMWP"]):
            # Keep explicit Eq./equation references too.
            if not re.search(r"\b(eq\.?|equation)\b", line, re.IGNORECASE):
                continue

        for label in sorted(labels):
            records.append((label, page_number, line))
    return records


def extract(pdf_path: Path, out_dir: Path) -> tuple[Path, Path]:
    reader = _load_pdf_reader(pdf_path)

    full_text_path = out_dir / "full_text.txt"
    equation_index_path = out_dir / "equation_index.md"
    out_dir.mkdir(parents=True, exist_ok=True)

    full_text_parts: list[str] = []
    eq_records: list[tuple[str, int, str]] = []

    for idx, page in enumerate(reader.pages, start=1):
        page_text = page.extract_text() or ""
        full_text_parts.append(f"\n\n===== PAGE {idx} =====\n{page_text}")
        eq_records.extend(_extract_equation_records(page_text, idx))

    full_text_path.write_text("".join(full_text_parts).strip() + "\n", encoding="utf-8")

    unique_records: list[tuple[str, int, str]] = []
    seen: set[tuple[str, int, str]] = set()
    for rec in eq_records:
        if rec not in seen:
            seen.add(rec)
            unique_records.append(rec)

    unique_records.sort(key=lambda rec: (rec[1], rec[0]))

    lines = [
        "# Equation Index",
        "",
        "Generated by `tools/extract_thesis_text.py`.",
        "",
        "| Label | Page | Raw form |",
        "|---|---:|---|",
    ]
    for label, page_num, raw in unique_records:
        escaped = raw.replace("|", "\\|")
        lines.append(f"| `{label}` | {page_num} | `{escaped}` |")

    equation_index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return full_text_path, equation_index_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--pdf",
        type=Path,
        default=Path("Ribarik-PhD-Thesis.pdf"),
        help="Path to thesis PDF.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("data/thesis_text"),
        help="Output directory for extracted artifacts.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.pdf.exists():
        print(f"ERROR: PDF not found: {args.pdf}", file=sys.stderr)
        return 2

    try:
        full_text, eq_index = extract(args.pdf, args.out_dir)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 3

    print(f"Wrote: {full_text}")
    print(f"Wrote: {eq_index}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
